os: linux
language: python
jobs:
  allow_failures:
    - python: 3.9-dev
  include:
    - language: python
      python: 3.6
    - language: python
      dist: xenial
      python: 3.7
    - language: python
      dist: xenial
      python: 3.8

install:
  - pip install -U pip setuptools coverage flake8
  - pip install -e .[sanic,flask]

script:
  - flake8 setup.py src
  - coverage run --include=src/* -m unittest repodono.model.tests.make_suite
  - coverage report -m
after_success:
  - pip install coveralls
  - coveralls
branches:
  only:
    - testing
    - master
    - 1.0.x
