name: build

on:
  push:
    branches:
      - master
      - testing
      - 1.0.x
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9, "3.10", pypy3]
        exclude:
          - os: windows-latest
            python-version: pypy3
          - os: macos-latest
            python-version: pypy3

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install coverage flake8
        python -m pip install -e .[sanic,flask]
    - name: Lint with flake8
      run: |
        flake8 setup.py src
    - name: Test with unittest
      run: |
        coverage run --include=src/* -m unittest repodono.model.tests.make_suite
        coverage report -m
    - name: Coveralls
      if: ${{ matrix.os == 'ubuntu-latest' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python -m pip install coveralls
        coveralls --service=github
